services:
  spark-etl:
    build: .
    container_name: spark_etl
    volumes:
      - ./data:/opt/app/data
    env_file:
      - .env
    command: spark-submit src/main.py

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: spark_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_TOKEN=dev
