version: "3.9"

services:
  spark-etl:
    build: .
    container_name: spark_etl
    volumes:
      - ./data:/opt/app/data
    environment:
      - RAW_PATH=/opt/app/data/raw/posts.json
      - OUTPUT_PATH=/opt/app/data/processed/posts_parquet
    command: spark-submit src/main.py

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: spark_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_TOKEN=dev
